% build_corridor_pinch_scenario.m
% Try to create a real .rrscene from CorridorPinch.xodr using RoadRunner MATLAB API.
% If RoadRunner connector is unavailable, generate a deterministic parametric trace CSV
% and write a small manifest indicating fallback was used.
%
% Config (robust path handling across working directories)
thisDir = fileparts(mfilename('fullpath'));
if isempty(thisDir), thisDir = pwd; end
repoRoot = fullfile(thisDir, '..');

projectRoot        = repoRoot; % repo root or explicit path
sceneRelPath       = fullfile(thisDir, "CorridorPinch.rrscene");
xodrRelPath        = fullfile(thisDir, "CorridorPinch.xodr");
traceCsvPath       = fullfile(thisDir, "CorridorPinch_parametric_trace.csv");
fallbackMarkerPath = fullfile(thisDir, "CorridorPinch_fallback_manifest.txt");

% Scene params (deterministic)
roadLength  = 100;
ego_start   = [0, 0, 0];
agent_start = [45, -4, 0];
agent_end   = [45,  4, 0];
agent_speed = 1.5; % m/s
sample_dt   = 0.1; % 10 Hz parametric fallback

try
    % Check for roadrunner API presence
    if exist('roadrunner','file') ~= 2 && exist('roadrunner','builtin') ~= 5
        error("NoRoadRunnerAPI:Missing","RoadRunner MATLAB connector not available in this MATLAB environment.");
    end

    rr = roadrunner(projectRoot); % connect to RoadRunner app/project
    fprintf("Connected to RoadRunner at %s\n", projectRoot);

    % If scene already exists and is large enough, open+report and exit
    if isfile(sceneRelPath)
        info = dir(sceneRelPath);
        if info.bytes > 50*1024
            fprintf("Existing rrscene present (%d bytes). Opening to verify...\n", info.bytes);
            openScene(rr, char(sceneRelPath));
            fprintf("Scene opened successfully. No changes made.\n");
            return;
        end
    end

    % Import XODR (deterministic geometry source)
    if ~isfile(xodrRelPath)
        error("MissingXODR:FileNotFound","%s not found; cannot import.", xodrRelPath);
    end

    fprintf("Importing XODR: %s\n", xodrRelPath);
    opts = openDRIVEImportOptions(); % will use defaults; adjust if needed
    importScene(rr, char(xodrRelPath), "OpenDRIVE", opts);

    % Save scene (overwrites placeholder)
    fprintf("Saving rrscene: %s\n", sceneRelPath);
    saveScene(rr, char(sceneRelPath));
    fprintf("Saved rrscene successfully.\n");

    % Quick programmatic verification
    info = dir(sceneRelPath);
    if info.bytes < 50*1024
        error("SavedButTooSmall:SuspiciousSize","Saved rrscene is too small (%d bytes).", info.bytes);
    end

    fprintf("Verification: rrscene size = %d bytes (OK).\n", info.bytes);

catch ME
    % On any error, produce deterministic parametric trace and manifest
    fprintf("RoadRunner API path failed: %s\n", ME.message);
    fprintf("Falling back to deterministic parametric trace CSV at %s\n", traceCsvPath);

    % Parametric trace: Ego moves along x from 0 to roadLength at constant pace (no acceleration model)
    t_end = roadLength / 5; % arbitrary ego speed 5 m/s for trace; deterministic choice
    t = 0:sample_dt:t_end;
    ego_x = min(ego_start(1) + 5*t, roadLength);
    ego_trace = [t', ego_x', zeros(size(t')) , zeros(size(t')) + ego_start(3)]; % [t, x, y, z]

    % Dynamic agent crossing from start to end at agent_speed
    dist = norm(agent_end(1:2)-agent_start(1:2));
    t_agent = 0:sample_dt:(dist/agent_speed);
    agent_x = agent_start(1) + zeros(size(t_agent));
    agent_y = agent_start(2) + (agent_end(2)-agent_start(2)) .* (t_agent/(t_agent(end)+eps));
    agent_trace = [t_agent', agent_x', agent_y', zeros(size(t_agent'))];

    % Write CSV with deterministic columns and a header
    fid = fopen(traceCsvPath,'w');
    fprintf(fid,"# Parametric fallback trace generated by build_corridor_pinch_scenario.m\n");
    fprintf(fid,"# ego_start=%g,%g,%g agent_start=%g,%g,%g agent_end=%g,%g,%g sample_dt=%g\n", ...
            ego_start, agent_start, agent_end, sample_dt);
    fprintf(fid,"type,time_s,x_m,y_m,z_m\n");
    for i=1:size(ego_trace,1)
        fprintf(fid,"ego,%.3f,%.6f,%.6f,%.6f\n", ego_trace(i,1), ego_trace(i,2), ego_trace(i,3), ego_trace(i,4));
    end
    for i=1:size(agent_trace,1)
        fprintf(fid,"dynamic_agent,%.3f,%.6f,%.6f,%.6f\n", agent_trace(i,1), agent_trace(i,2), agent_trace(i,3), agent_trace(i,4));
    end
    fclose(fid);

    % Write manifest marking fallback used
    fid = fopen(fallbackMarkerPath,'w');
    fprintf(fid,"fallback_used=true\n");
    fprintf(fid,"reason=%s\n", strrep(ME.message, newline, ' '));
    fprintf(fid,"trace_csv=%s\n", traceCsvPath);
    fprintf(fid,"timestamp=%s\n", datestr(now,'yyyy-mm-dd HH:MM:SS'));
    fclose(fid);

    fprintf("Parametric trace and manifest written. Exiting with fallback.\n");
    return;
end
